### ISSUE TITLE
🆕 Help new users see/access a step-by-step guide to configure Blowfish

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#1101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knowinginner** [comment]
# 👋 Hello dear Nunocoracao

# 🎉 I have tried Blowfish several times due to design characteristics which I like:

- masonry
- author widget in post
- amazing blurry images in posts and theme
- completely stunning table of content
- social 
- related posts
- nav next previous navigation
- dropdown menu
- shortcodes
- tailwind
- response from developer and owner
- documentation

🚧 I have used bootstrap theme wowchemy/academic and realized that I would like to maintain pure hugo  adding content to frontmatter by hugo cascade and using  tailwind populate components such as hero, feature, FAQ, etc.

## 🛑 I have tried with partial success to port hero from [tw-elements](https://tw-elements.com/) as `package.json is using lib/tw-elements/index.min.js `

### I have found out:
- tailwind grid is off
- buttons doesn't display
- forms doesn't follow the theme
- components 

## 🚏  Alternatives

- I have considered using hugoplate which allows initially tailwind elements and it isn't well documented
- I have considered learning hugo and in 3 to 8 months have knowledge about what it's proper.
- I have considered using HTML to change colors, padding, margins

# 🙏🏽 I would like your guidance how to implement full tailwind CSS

Thanks Very much

### 🌻 Faust

**Comment by nunocoracao** [comment]
Hello @knowinginner I don't think your comment is related to this issue. Please move it into the discussions section so that I or someone else can help.
