### ISSUE TITLE
✨Integrate against subscription systems

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#128]
**Is your feature request related to a problem? Please describe.**
Integrate against subscription systems

**Describe the solution you'd like**
A way to setup a notification system for readers to get updates when a new blog posts is released

**Describe alternatives you've considered**
3rd party solutions

**Additional context**
n/a

**Comment by nunocoracao** [comment]
Not clear if this is something that should be 
1) fixed in the theme (most likely not)
2) support integrations with 3rd party services
3) not support and handled as custom integrations/extensions

**Comment by AvinashReddy3108** [comment]
> A way to setup a notification system for readers to get updates when a new blog posts is released
RSS feeds (already implemented) 👀

**Comment by nunocoracao** [comment]
@AvinashReddy3108 thanks for the feedback. I know but doesn't appear that people use RSS that much. Trying to understand if there are other options to explore (browser notifications). Also it should probably have a place in the theme to create those subscription buttons.

**Comment by mirceanton** [comment]
I think the easiest solution would be some sort of email list style software that will listen to the RSS feed and then send an email once a new post is published. This could be implemented as something external to the theme itself.

Maybe some template in a common programming language, like javascript, for example, so that others can write their own implementations if needed (say i have a discord community, i can make a discord bot to notify users).

**Comment by nunocoracao** [comment]
It seems that the conclusion of this thread is that there is little that Blowfish itself should do about this... Unless there are already services out there that we could implement PnP integrations for in config files (like firebase). Thoughts?
