### ISSUE TITLE
Difficult to use a custom Highlight color scheme

### ISSUE THREAD

**Issue by chrisbanes** [nunocoracao/blowfish#142]
**Describe the bug**
Currently the Tailwind config sets a number of Highlight/chroma styles. This makes it difficult to use a custom highlight scheme via the `custom.css`. Personally, I'd much rather set the syntax highlight vs having it reflect the overall site color scheme

**To Reproduce**

`hugo gen chromastyles --style=dracula > assets/css/custom.css`

**Expected behavior**
Preformatted text uses the defined theme.

**Comment by nunocoracao** [comment]
Hello @chrisbanes, this one I need a little time with. I also want to switch up the overall color scheme css mechanics but haven't found a way to do it. If you have any implementation ideas feel free to share

**Comment by chrisbanes** [comment]
I only way I can think of is to remove all of the highlight styles from Tailwind, and then import one of the normal Chroma CSS styles as a default.

That way people can use whatever Chroma style they want, which will overwrite all of the default styles.

**Comment by nunocoracao** [comment]
Need to investigate this, I think there is value is providing the current default but it needs to be extendable...

**Comment by nunocoracao** [comment]
Hello @chrisbanes I am closing this one. 
Hugo already supports a way to do this. Check [here](https://gohugo.io/templates/render-hooks/#render-hooks-for-code-blocks). Hugo has a render hook for codeblocks. You can create one that will override the theme ones and import the right .chroma classes.

**Comment by deltaclock** [comment]
Pretty new to Hugo. I'm unaware if there's something better currently but I've managed to in-cooperate both the theme's codeblock style and the one  from `chromastyles` with `layouts/_default/_markup/render-codeblock.html` as:

```html
{{ $class := cond (isset .Attributes "usetheme") "chroma" "chroma-custom" }}
{{- if transform.CanHighlight .Type }}
<div class="highlight"><pre tabindex="0" class="{{ $class }}"><code class="language-{{ .Type }}" data-lang="{{ .Type }}">
{{- with transform.HighlightCodeBlock . -}}
    {{ .Inner }}
{{- end -}}
</code></pre></div>
{{- else -}}
<pre tabindex="0"><code class="language-{{ .Type }}" data-lang="{{ .Type }}">{{ .Inner }}</code></pre>
{{- end -}}
```

Generate `chroma-custom` with `hugo gen chromastyles --style=dracula | sed -e 's/chroma/chroma-custom/g' > assets/css/custom.css`

You can set `usetheme=1` on a codeblock to use the internal chroma style from the theme, otherwise by default it uses the custom one.

***

Unfortunately, this *kinda* breaks the Copy button as a newline is added on the copied text due to `.line {   display: flex;}`.
This can, again, be fixed by replacing `innerText` with `textContent` here: https://github.com/nunocoracao/blowfish/blob/3a50c14d2fac08ac58c728463b3098da81198428/assets/js/code.js#L16

If @nunocoracao wishes I can create a PR to use `textContent` by default; it doesn't seem to cause any issues even with the default chroma theme.

**Comment by 0xNoNames** [comment]
@deltaclock Note that this code will break any [Hugo's highlight options](https://gohugo.io/content-management/syntax-highlighting/#highlight-shortcode),  such as `{linenos=true}`.
