### ISSUE TITLE
🖌️ Long ToCs not shown fully

### ISSUE THREAD

**Issue by wermos** [nunocoracao/blowfish#1474]
## Description

A good example of the bug is in the documentation itself, [here](https://blowfish.page/docs/configuration/). When the table of contents is really long, it is impossible to see all the options until you scroll to the bottom of the page.

## Expected behavior
One relatively simple solution I can think of, is to make the ToC scrollable, independent of the main page's scroll.

## Screenshots
![image](https://github.com/nunocoracao/blowfish/assets/63574588/0ed758ba-f9bc-4e7f-95fa-40c533bb97a3)

In the above screenshot, it is not possible to see the text below "Firebase" until you scroll to the bottom of the page.

**Desktop (please complete the following information):**
Even though I don't think it's applicable here, I'll fill it regardless.
 - OS: Windows 11 23H2, OS Build 22361.3447
 - Browser: Edge
 - Version: 124.0.2478.80 (Official build) (64-bit)

**Comment by maciejopalinski** [comment]
The table of content definitely should **NOT** be scrollable independently of the main page's content. It would look very bad.

**Comment by wermos** [comment]
My proposed solution was just the first thing that came to mind. I am open to other solutions.

**Comment by Usual-Coder** [comment]
Hi,

Even if we are a minority, may we disagree on the _bold_ (subjective) statement "(...it) should **NOT** be scrollable (...) It would look very bad" ?!

Typing "Best Practices" + "Table of Contents" in your preferred search engine may show you how many (different) opinions you can have about the _"how to do things properly"_.

That being said, **the purpose of a ToC is to provide a way to be able to _"jump"_ quickly anywhere in your document** (online / offline ... or even printed = your fingers doing the same job as your browser 😅).

So, even if a majority disagree, some of us may be allowed to think that making it available only partially (I agree the configuration page of Blowfish website is not _that_ big 😅 ... but it was just an example) is not the best/expected behavior.

The same way, @nunocoracao may not give a damn about it, think it's too much work for a too small audience ... or have other priorities 🤷

In worst case, we'll have to switch to another (rare) theme providing this kind of feature, mainly for docs (like [Doks](https://themes.gohugo.io/themes/doks)) or learning (ex.: [Relearn](https://themes.gohugo.io/themes/hugo-theme-relearn)), but, on a more _subjective_ point of view, most of them are not as nice/_polished_ as Blowfish 😅

On a more constructive note (having filled the issue #1455, marked as `closed` a little too fast 😇, for the very same reasons), may I propose: (in order of priorities, as I see them)

1. at least a `smartTOCPosition` configuration entry, so those producing _big documents_ can benefit from a _"full ToC"_ placed at the beginning/end, **the same way Blowfish handles posts [series](https://blowfish.page/docs/series)** = the behavior / _responsiveness_ / etc. being already implemented, it should be easily adapted 🤔

2. to keep the ToC _"in sync"_ with the main content (the anchor in the main panel should be visible in the ToC lateral panel)

3. a `smartTOCBehavior` configuration entry, allowing `collapsible` and/or `scrollable` ... for those who like it that way 😅

May I end by saying that the choice should always be given to users. But time being such a rare commodity, as always, @nunocoracao will have the final say ... thanks for considering this 🙇

**Comment by maciejopalinski** [comment]
> Even if we are a minority, may we disagree on the _bold_ (subjective) statement "(...it) should **NOT** be scrollable (...) It would look very bad" ?!
> 
> Typing "Best Practices" + "Table of Contents" in your preferred search engine may show you how many (different) opinions you can have about the _"how to do things properly"_.

I have never seen a scrollable table of contents placed in similar way like the one in Blowfish. I suppose that's for a reason, because it would be an objectively  bad design choice. If you think otherwise then show some examples on other websites and implement it in Blowfish as a proof of concept.

**Comment by Usual-Coder** [comment]
I'm not here to convince people who own the absolute truth to be more open-minded or take a better look at what is available outside.

And, no matter this too often passive-aggressive attitude we bump into, when discussing different opinions, and the way of presenting your own as the only possible way of thinking, since I don't pretend to own it myself but merely consider a constructive approach to (start with) fill(ing) issues and try improving things by doing so, maybe we should let @nunocoracao answer this one by himself ?!

And as I said previously / many times in other issues, if he thinks it's not appropriate to fix/add this feature to this project/theme ... that's more than ok 🤷

Blowfish is already a very good theme and we are all thankful for his time and the fact he is providing it freely to the community (and can also add thanks for you 2 commits last year and the other ones who helped him, no matter how (much) they've contributed) 🙇

For those who may be unhappy with his answer and/or the availability/knowledge/whatev to implement this feature, they'll still have the possibility to search for a better-fitting theme 🤷

Hoping for an answer soon so we can stop wasting time/energy talking about it and more building/producing things 🤷

Best regards to you all. 🙇

**Comment by maciejopalinski** [comment]
> I'm not here to convince people who own the absolute truth to be more open-minded or take a better look at what is available outside.
> And, no matter this too often passive-aggressive attitude we bump into

There is nothing passive-aggressive about my simple request for a proof of concept when suggesting a change. That is just how open source software development works.
[How to contribute to Blowfish: New features & enhancements](https://github.com/nunocoracao/blowfish/blob/main/CONTRIBUTING.md#new-features--enhancements)

**Comment by wermos** [comment]
@maciejopalinski Do you agree that not being able to see the full ToC is a problem? If not, why not? If yes, then do you have any suggestions that are not, in your words, "an objectively bad design choice"? Since I am not a designer, and I suspect @Usual-Coder is not either, could you please enlighten us about some good design choices?

**Comment by maciejopalinski** [comment]
That looks cool, but it would require to move the ToC to the left. I don't think it necessarily fits the theme. I think the theme was designed mainly with blogs in mind in which you won't really find such long ToCs.

**Comment by Usual-Coder** [comment]
Hi,

@wermos thanks for your additional input. I decided to cut my losses with Hugo/theming/etc. (too much time lost with the tooling instead of producing content) = at least for now, I'll use another solution :shrug:  But, still, I think Blowfish is probably one of the best themes for Hugo :bow: (after all, it's just not fitting our needs / decisions had to be made :shrug:)

To try ending on a constructive note, I'm providing a link to a French website behaving as I expected initially (ToC on the right being **scrollable and really kept in sync with content**):

- https://cours.brosseau.ovh/tp/typescript/api.html 
- **_Global_ navigation on the left** (as described by MDN for [`nav`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/nav) element)
- **_Document "navigation"_** -aka _"ToC"_- **on the right** (no matter how it's translated in HTML/CSS, a _generic_ div as it's done right now, an [`aside`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/aside) element as described from the very same MDN, or any adequate element / styling to achieve this goal)  ... **as expected by anyone writing/producing docs/webpages/whatev with AsciiDoc when `:toc: right` is set**
- additionally, the linked website / ToC has a very useful (discreetly/nicely integrated ?!) _indicator_ (the vertical bar in front of the displayed/actual _entry_) making it easy to know _how far_ you are in the document ... easing things from the reader point of view :thinking: 

I also still understand that @nunocoracao may not have time to implement that (making his `smartTOC` scrollable, at least as an option, and kept in sync with the main content). As I said, it's his prerogative to determine if it's bug or enhancement ... and how to handle it :shrug: I hope he will fix/add this feature :crossed_fingers:

Best regards to you all

**Comment by maciejopalinski** [comment]
> * https://cours.brosseau.ovh/tp/typescript/api.html

This one convinced me, I didn't even realize it was scrollable at first, but then I checked and it really is. I apologize for misunderstanding the idea that you suggested. It would definitely be a nice fix/addition to have this indicator and make it scrollable (preferably auto-sync with content; without the scrollbar visible of course).

**Comment by Usual-Coder** [comment]
@nunocoracao ... if you consider implementing this after all, from the UX designer point of view, to handle _sublevels_ (not presented in the linked URL), may **I also suggest replacing** (or providing a `SmartTOC***` option) **your underlined style** (some may say we could call it a _horizontal bar_ :smirk:) **with the vertical bar shown in the linked website**.

By doing so, you could **_"expand"_ it in front of the subentries and _handle_ sublevels, adding a similar** (expandable, if needed / _children_) **but _"sub-leveled" bar_, using a darker color from your palette depending on the sublevel** (the most vivid being the deepest one ... aka _"keep the focus where it's needed + make the rest useful but discrete"_ :smirk:).

I'm about to go out right now, if my explanations are not good enough, I may search for an example + add a comment with a link later. Just ask.

**Comment by wermos** [comment]
@Usual-Coder thanks for the example. I can use this to deconstruct how Vitepress does it and perhaps open a PR in Blowfish to implement the same feature. Vitepress's default ToC works exactly how I envisioned the feature to be.

> I think Blowfish is probably one of the best themes for Hugo

I wholeheartedly agree. @nunocoracao has done some amazing work here.

The
> "sub-leveled" bar

idea sounds pretty interesting to me. I'll play around with it and see if I can implement it along with the Vitepress-style scrollable ToC.

Do you also have an idea for what darker color from the palette could be used here? More specifically, could you help me figure out which color to use for the default blowfish color scheme and the other available skins?

> ...if my explanations are not good enough, I may search for an example + add a comment with a link later. Just ask.

It would be nice if you could find a site that uses the "sub-leveled" bar so that I have a visual example to go by.

**Comment by Usual-Coder** [comment]
@wermos: I didn't do much ... that _design_ (scrollable/synced right ToC) is quite common 🤷

To stay around Hugo:
https://docs.gethyas.com/install/auto/#starter-templates
> The guys from [Hyas](https://gethyas.com) are the ones behind the [Doks](https://getdoks.org) theme for Hugo
> Some would also notice the very nice idea 😇 of the [_"tabbed"_ code block](https://docs.gethyas.com/install/auto/#official) (allowing to switch between _variants_, also used on [Hugo website](https://gohugo.io/content-management/build-options) ... btw, even if it's not that long/useful there, the right ToC is also scrollable ... if it's good for Hugo's daddy maybe it could be good for us 🤷😅) = that could also be a _killing feature_ for Blowfish 🤐😇😅


Another one I came across while dealing with what is actually requiring my attention:
https://elysiajs.com/patterns/websocket.html (behaving the exact same way as the French blog linked previously ... but I prefer the _homogeneity_ of the linked Blog, nav/toc sharing the same _design_)
> btw, (as shown by the first entry) an option to handle the text overflow of entries too large with an ellipsis could also be an idea to _explore_ 😇 ... but (unlike them) with a mouseover animating the text _in place_ instead of popping a _basic_ tooltip ... as always, with design _considerations_, the devil / _wow effect_ is in the details / how seamlessly everything is integrated (and/or configurable one would argue)

Right now, I don't have time to search specifically for _sublevel_ design examples, but **if I stumble upon a website having such a design, I'll try to remember to provide you with a link ✔**

Btw, I can't help you with colors/palette considerations. First, because I think it's @nunocoracao prerogative to answer that one. And second, it would require me to read Blowfish code ... which is the very reason I decided to steer away from Hugo/theming/etc., having already lost too much time ("(...) with the _tooling_ instead of producing content (...)", as I put it earlier 😇).

No matter what, wanting to contribute to Blowfish code base is a very constructive way to handle this issue ... big respect for that 🙇 ... but may I suggest starting with a _quickwin™_ until @nunocoracao comes _in the loop_ ... and gives his point of view on the subject?! 🤐😇

In the meantime, I would stick with a _basic_/_simpler_ version like the one available here (getting the _inspiration_ from the left panel/_nav_): https://bun.sh/docs/bundler/loaders#json
> Take a good look at the indicator**S** ... couldn't it be a good _compromise_ until you hear back from @nunocoracao about how far you'd be allowed to alter Blowfish design?! 🤐😇🤷

At the end of the day, it's your time, feel free to push the envelope ... that's how great things are built 😅🙇

**Comment by nunocoracao** [comment]
Oh geez... this was a long one. A couple of comments here (sorry if I jumped over some parts this was a long thread to catch up with)
- thanks @wermos for raising this, I do think is a valid problem and by explaining the pain you're feeling I can think of a solution - either the scroll or something else. And I would be really happy to review a PR with your proposal.
- thanks @Usual-Coder thanks for keeping the discussion in check and positive all the time. And I am sorry that you are not using Blowfish any longer :P - even though I 100% get your comment.
- thanks @maciejopalinski for being passionate about this issue 

Now, my take on this discussion. I do believe this should be implemented - I will need some time though :D 
A couple of points on how I see the solution
- In my head, this is an edge case and people having the problem are ok with a "scrolling" solution and I think there are ways of implementing one that makes sense for the rest of the theme - @Usual-Coder provided some good suggestions here.
- I don't think this should be another-config - the theme is getting bloated with too many configurations and it seems we are discussing a solution for a problem that doesn't have "a" solution at the moment.
- I would implement this in a way that current use cases stay the same i.e. no breaking changes for existing users
- ...and in a way that it changes when needed to accommodate long content i.e. without configs

If the above is not possible, aka it requires redesign than the second best option is to add another config... 

Were you planning on working on a PR or do you want me to take this on? - to be clear, it will take me a while to have time to focus on this particular one

**Comment by wermos** [comment]
Thanks for the response, @nunocoracao!

> Sorry for not getting back to any of you sooner. 

No worries. Better late than never 😄

> Were you planning on working on a PR or do you want me to take this on?

I would feel better if you took this on. I'm only beginning to familiarize myself with the repo, so I'm more comfortable with bug fixes and the like. I spent some time looking at the existing ToC implementation, and I think that fixing this would require me to rewrite the `layouts/partials/toc.html` file.

**Comment by Usual-Coder** [comment]
@wermos I'm sorry, I didn't have time to find an example + I'm probably going to unsubscribe soon = won't receive further messages. Having only a draft on how to derive/create a Hugo theme (finishing it is now at the very bottom of my TODO = no task/time will be allotted, at least for a few months), I can't help you further. Sorry. I hope you'll find your own solution.

To end this part on a constructive note / trying to help you contribute ... or build your own solution:
- If you're not familiar with the _merging_ process used by Hugo (aka how it handles _everything_ / its _virtual filesystem_, even for imported themes), **it could be a good way to start trying to fix/enhance Blowfish** = you can _overwrite_ every file of Blowfish(/any) theme, to **test the impact of your modifications _on-the-fly_ + using [(Hu)Go modules](https://gohugo.io/hugo-modules)** (instead of messing with git submodules = take a look at ["Use Hugo Modules"](https://gohugo.io/hugo-modules/use-modules)  and ["Theme components"](https://gohugo.io/hugo-modules/theme-components) sections) will probably help you work more _efficiently_ on a solution ... and its distribution ... until PR are accepted ... or not 🤐😇
- To improve the _on-the-fly_ part, **using a containerized Hugo would probably help with the trial/error process**.
- No "official" image being maintained/documented, if you're familiar with containers, **I** would **STRONGLY suggest building your own**. If not, it pains me (I don't like recommending things I'm avoiding myself 😏) to say that [HugoMods](https://docker.hugomods.com) images are probably the most useful images available, **at the moment** 🤷. Don't get me wrong, like everyone giving resources freely to the community, I have great respect for [the guy](https://razonyang.com/zh-hans) behind [HugoMods](https://github.com/razonyang) 🙇. The _pain_ is coming from how such kind of images are built! 🧐😱 In this very case, while fully automated, relying on an [_exotic_/unmaintained syntax](https://github.com/hugomods/docker/blob/main/docker/hugo/Dockerfile)/process + the lack of _privileges de-escalation_, etc. ... aka the why you should do it by yourself, if you know how to (actually I wasted a lot of time there too, to the point I had to contribute to `docker/buildx` `bake`, _learning_ Go in the process, while trying to create an alternate _pipeline_ relying on an up-to-date/maintained solution = yep I got upset wasting so much time 🤬🤯, I thought wasting even more, trying to fix hardcore stuff / building _the missing piece_, was the good solution 😅 ... let's just say cutting my losses with Hugo/Blowfish&co has been painful in many ways 🤐😞)

Besides those _pointers_, I'm sorry I can do much more + I probably won't contribute to Blowfish anyway (if I come back near Hugo / these kinds of time-consuming topics, it will probably mean creating a new theme / everything else to fit my needs) = still **I think it's one of the best theme around** worth your time / contribution(s) 🤷 Have fun _playing_ with it 😅

@nunocoracao thanks for your answer and don't get me wrong on the _"I would prefer to create my own"_ = I was hoping to _fill a gap_ with Hugo/Blowfish until I had a proper LMS, up and running (some of my needs are related to courses/learning process = I can't afford not having tables of contents behaving the way they should + missing other useful features = the fixing/adding time has to be put in doing it directly in the LMS) = I'm mean it, great job with this theme 🙇. Hope you'll be able to find the time to keep it evolving ... and hopefully the necessary help/contributors 🤞

Best regards to you all 🤘

**Comment by nunocoracao** [comment]
@wermos @maciejopalinski @Usual-Coder feel free to have a look at https://github.com/nunocoracao/blowfish/pull/1529
A preview link should be there soon to see the differences... this was wayyyyy harder than I expected. 
Thanks for suggesting this though got to learn some sutff

**Comment by Usual-Coder** [comment]
@wermos: I thought about creating an example design for you (not having time to read Blowfish code, opening something like Figma seemed rapidly overkill / too far fetch) ... but, since we are never safe from an unexpected/pleasant surprise 😅 ... while answering @nunocoracao I stumble on an example of _"sublevels handling"_ (with vertical indicators) 😅🎉 from one of the previously linked examples = https://elysiajs.com/eden/treaty/overview.html ... on the left (used for _global navigation_ ... but you can extrapolate it for a ToC 😅). I personally like _minimalistic_ designs, so I would consider keeping it even more simple = trying to show only the _deepest_ vertical bar + hide the _highest_ one (replacing it with the same _vertical indicator_ in front of the _opened_ entry). I wouldn't add/mess with the background color (you could consider it _useful_ when trying to keep the info about the _main_ stuff, as it's done on this example ... but I would keep a _low/discrete profile_ for the ToC). (Instead) I would also _play_ with the alpha component of the font (aka _opacity_) = darkening _out of reach_ entries (obviously restoring full white/black on mouseover) + bold lettering for the _parent_ entry, when opened, and the _current_ one (the child/shown entry) = yep _collapsible_ entries are definitively a must-have with _"big docs"_ ... but that part may also require a lot of work 😇 Remembering, those are only suggestions + opinionated/subjective considerations = I don't own any truth ... feel free to contribute while ignoring them completely 🤷 @nunocoracao is paving the way for many possibilities, don't be afraid to try new things 😉

Just found another example showing something very similar to what I just wrote (ignore the ToC, inspiration could be taken from the navigation on the left): https://clerk.com/docs/authentication/social-connections/gitlab. And this incredible variant (take a look at the ToC on the right), so simple but efficient: https://clerk.com/docs/custom-flows/user-impersonation#revoke-an-actor-token-from-the-backend-api 😱🤩

@nunocoracao (even if I'm not coming back to Hugo/Blowfish, I took a _rapid look_ at your files changes = too many modifications = don't have time to check the PR _technically_ ... Sorry 😞) I'm impressed by your commitment to improve this theme. Great respect for that 🙇 You deserve the interest your theme is picking. I hope you'll get the _traction_ it really deserves 🤞

Now, concerning the PoC/_preview_ you've provided in the PR (doing such a thing/producing this kind of effort is really _~amazing™~_ mesmerizing), the following remarks are made per your request (if something is not clear, ask for additional precisions 😅😇):

1. Per UX _fundamentals_ , given an _optional_ component (scrollbar), it shouldn't be displayed when it's not needed / could be confusing (like 2 scrollbars too close) ... aka _"keep the UI _clean_ as much as possible"_ + _"show only what's necessary"_. Examples linked above don't show any scrollbar = the _scrollable area_ is _triggered_ depending on mouse position = It's not _technically_ needed ... but, as always (it's your prerogative), you could argue you prefer it your way for other reasons (design/whatev)?! 🤷 Your _main_ scrollbar is not shown when it's not needed (ex.: [authors page](https://blowfish-21fff--preview-1529-l4elchm8.web.app/authors)) ... if you want to keep the ToC scrollbar, shouldn't you apply the same logic everywhere?!

On a more _subjective_/opinionated note, I would have it removed completely + the underline in the Toc is too strong (for my own taste) = I would replace both with vertical indicator(s) in front of the entry(ies), as shown in linked examples.

2. Improving UX (would probably require even more additional rework 😅😇): a ToC must answer the _"where you are"_ but it could also show the _"what is (actually) covered"_ (like https://bun.sh/docs/bundler/loaders#toml) or point/indicate the _"where you go"_ (useful in _learning/teaching context_, aka tutorials, courses, processes, etc.), like https://clerk.com/docs/quickstarts/fastify. For that last variant, you could already achieve something quite similar with your Timeline shortcode, for the main page = the _ordered ToC_ is the only missing component 🤐😇

Hope this feedback will help your reflection. 🤷

**Comment by nunocoracao** [comment]
Thanks @Usual-Coder.

Regarding the design perspective I will definetly play around with it. I also don't like the huge blocks - it came with the lib. 

I relied on the markdown sample article and reduced the height of the window to test this. Behavior should be, no scroll when TOC is smaller then height of window - otherwise scroll becomes visible... are you seeing something different?

**Comment by Usual-Coder** [comment]
### Short answer
_"no scroll when ToC is smaller than the height of window"_ may be good enough, for now = it will fix the issue = **take the** (quick)**win** 🤷 (and start **a discussion _"somewhere else"_** about design + UX considerations with users willing to have constructive contributions / being a force of proposal ... or simply sharing design inspirations 🤷). 

### Not so short answer 😏
It may not be that simple, depending on what you want to do with it 🤷 I started a _detailed_ answer ... but this issue, already quite long 😅, would have exploded 😇 = obviously (theoretically) you'll always have: `ToC` (aka component) `max-height` < `(...)` < `window` `height` (aka _presentation_ area). The `(...)` representing (**optional**) things you probably didn't consider/think to implement (for now 🤷).

But, as always, **the devil is in the details** 😏

Let me give you an example _outside_ of considerations regarding the ToC itself. If we call the ToC a `component` (not the worst idea, some would say 😅😇) and its parent container a `panel` (avoiding considerations related to the _layout_, for the sake of this example / to keep it _short_ 🤐), **you may put other components in that panel** = a (quick)search form/entry at the top, additional/useful links at the bottom, etc. (take a look at the links) ... you could even have other components right in the middle of the ToC (we are talking evil here ... let's consider ads for those who may try that to _monetize_ their blog / would still think it's possible/sufficient to cover their costs with that kind of annoying things 🤐) = you may have to deal with the _height distribution_ in different ways 🤷 (start having _playful_ usage of CSS variables and other things like that 😏)

Now, talking about the ToC only, you may try to make it really _smart™_ 😏 aka _dynamic_ ... (line-)height + fading/folding/animating _out of reach_ / unnecessary entries ... even better, not _showing_ the full ToC at all 😱 (may come handy for VERY long docs, procedures, etc.), but _adapting_ displayed entries (depending on the mouse position 🤔) ... etc.

= I could fill your (full-time) backlog for weeks (if not more) just on that topic  ... but, without knowing your (real) motivations + where you want to go with your work here (the _somewhere else_ / those discussions **may** be organized outside GitHub = try building a community around your work, etc. 🤷 yep ... let's just say, I'm a _pushing the envelope_ kind of person 😅), I think it's better to stick with the [Pareto principle](https://en.wikipedia.org/wiki/Pareto_principle) = fixing this issue, **you've probably done enough for your main** (aka the 80% 😉) **audience** 🤷 (and I must go back to my own troubles with very similar topics 😅)

Again, I hope it will help your reflection.

I wish you the best for the rest ... and thanks for the time / fixing this one 🙇

**Comment by wermos** [comment]
> feel free to have a look at #1529

Sorry I wasn't able to get to it sooner, I was a bit busy with some other things.

I took a look at it now, and I am quite satisfied with the result. It definitely addresses this issue in its entirety.

I also think that @Usual-Coder is correct, but further tweaking can always be done in later PRs. I think it's good enough for now. Great work!
