### ISSUE TITLE
使用 Algolia 作为站点搜索方案/Using Algolia as the site search solution

### ISSUE THREAD

**Issue by yoghurtlee-thu** [nunocoracao/blowfish#1495]
> Please view English version below.

如题，为了表述方便我没有按照 issue 模板书写，请原谅。

目前站点的 `Fuse.js` 方案对中文搜索支持并不尽如人意。在所有 Hugo 能够整合的搜索方案中，个人认为 [Algolia](https://www.algolia.com/) 是最高效且强大的（当然，Meilisearch 也很好，但是 Meilisearch 需要在服务器部署，大部分人可能没有这个条件）。

因此个人建议使用 Algolia 代替 `Fuse.js` 作为站点搜索方案，或者至少给用户选择的机会。

最后，感谢您为开发和开源这个美妙主题做出的努力。

此致。

---

Hello,

For the sake of convenience in expression, I did not follow the issue template when writing this, please forgive me.

Currently, the `Fuse.js` solution for our site's search does not support Chinese search very well. Among all the search solutions that can be integrated with Hugo, I personally think that [Algolia](https://www.algolia.com/) is the most effective and powerful (of course, Meilisearch is also wonderful, but Meilisearch requires deployment on the server, which most people may not have the conditions for).

Therefore, I personally suggest using Algolia to replace `Fuse.js` as the site search solution, or at least giving users the option to choose.

Finally, please allow me to express my sincere gratitude for your efforts in developing and open-sourcing this awesome Hugo theme.

Best regards.

**Comment by nunocoracao** [comment]
您好，感谢您的留言@yoghurtlee-thu，我很感谢您的努力，特别是考虑到语言障碍。 

我不会接受这张票，因为我没有时间维护这样的解决方案 - 添加另一个服务器端将需要整个站点的额外维护工作。 

这可以通过覆盖部署中的 search.js 文件轻松实现。只需更改获取搜索的方式 - 即执行 API 调用 VS 只调用熔断器。 

如果您希望将其覆盖在您的网站上，我们很乐意帮助您实现它。

--------

Hello thanks for your message @yoghurtlee-thu, I appreciate the effort especially given the language barrier. 

I will not be accepting this ticket since I do not have time to maintain such a solution - adding another server side will require extra maintenance work for the entire site. 

This can be easily achieved by overriding the search.js file in your deployment. Just need to change the way the search gets fetched - i.e. performing an API call VS just calling fuse. 

Happy to help you implement it if you want it as an override on your site.
