### ISSUE TITLE
🐛 JavaScript error "Uncaught ReferenceError: oid is not defined" is thrown when not using Firebase integration

### ISSUE THREAD

**Issue by ragibson** [nunocoracao/blowfish#1651]
**Describe the bug**
Pages with posts throw a ReferenceError in the console when not using a Firebase integration.

**To Reproduce**
View any Blowfish website without likes enabled and you'll see it in the console. Pulling a few arbitrarily from the Blowfish users page: https://joshblais.com/posts/, https://zen96k.github.io/enoshima-escar/posts/, https://blog.wtcx.dev/posts/, etc.

**Expected behavior**
No errors are thrown in the console.

**Screenshots**
![image](https://github.com/user-attachments/assets/39dc4cde-13ac-49ef-8b20-2b92e769e20f)
![image](https://github.com/user-attachments/assets/c087a684-1ebe-4a1d-bdb0-6e5f361f74c2)

**Desktop**
 - OS: Linux, Windows
 - Browser: Firefox, Chrome
 - Version: Most recent / various

**Hugo & Blowfish versions**
The most recent version, though it seems to affect a wide range of them.

**Additional context**
At a glance, this is probably caused by https://github.com/nunocoracao/blowfish/commit/6190898b7014684a6ca4961efaac25433bed7546.

**Comment by wtchangdm** [comment]
The problem is that https://github.com/nunocoracao/blowfish/blob/18ed67b2e613e2803d05b857327d73e408d90d53/layouts/_default/list.html#L29-L32 doesn't get rendered as expected so there is no `oid` and `oid_likes` to being with. Not sure what does this part try to do with the translations.

One way to simply suppress the error is to add some guards here:
https://github.com/nunocoracao/blowfish/blob/18ed67b2e613e2803d05b857327d73e408d90d53/assets/js/page.js#L1-L5

**Comment by ragibson** [comment]
I agree that the guards would work, but I've opted to just include the scripts in the relevant statement scopes to better target the root cause here. Let's see what nunocoracao says in the PR.
