### ISSUE TITLE
Potentially malicious link in Readme.md

### ISSUE THREAD

**Issue by BasilSkrnk** [nunocoracao/blowfish#1859]
I noticed that current [Readme.md](https://github.com/nunocoracao/blowfish/blob/main/README.md?plain=1) has a potentially malicious link. 

The line 149:

```
You will find these theme config files in the Hugo cache directory, or [download a copy](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/nunocoracao/blowfish/tree/main/config/_default) from GitHub.
```

- The current link: https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/nunocoracao/blowfish/tree/main/config/_default, the **minhaskamal.github.io/DownGit/#/home?url=** part looks very suspicious.
- My guess that the link that should be, is: https://github.com/nunocoracao/blowfish/tree/main/config/_default

----

The Firefox informs it like this.

![Screenshot-2024-11-30-163537](https://github.com/user-attachments/assets/3d598eb8-6b0e-4985-81c6-b21369d50fe9)

I’m not pull requesting, as maybe it’s the expected thing and this `DownGit` actually does something, hence this link is as it is.

I’ve tried to find which pull request added this line, but a quick search returned nothing useful. Possibly, it was merged into other file (e.g. installation instruction) which was merged with this Readme later on.

Chinese version has this link too.

**Comment by pranavnasrani** [comment]
just a guess @BasilSkrnk 
this downgit may just provide download links, and may in the past have been used to provide download links by a threat actor. this may not mean that the config/_default links are malicious. 

analogy: its like a website hosting platform that may have hosted malicious websites in the past, but this website is not malicious (no assurances there)

btw i downloaded them and they were fine (mostly) as long as i can identify

any particular reason why you want to download them? both `npx blowfish` and 'git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish` download the config/_default stuff now/.


again this is just a guess/attempt at explanation.




> I noticed that current [Readme.md](https://github.com/nunocoracao/blowfish/blob/main/README.md?plain=1) has a potentially malicious link.
> 
> The line 149:
> 
> ```
> You will find these theme config files in the Hugo cache directory, or [download a copy](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/nunocoracao/blowfish/tree/main/config/_default) from GitHub.
> ```
> 
> * The current link: https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/nunocoracao/blowfish/tree/main/config/_default, the **minhaskamal.github.io/DownGit/#/home?url=** part looks very suspicious.
> * My guess that the link that should be, is: https://github.com/nunocoracao/blowfish/tree/main/config/_default


i think the reason that @nunocoracao did not add link https://github.com/nunocoracao/blowfish/tree/main/config/_default is because github does not give a way to download all the files in the directory (all .toml files - as far as i can figure), hence he tried to make it easier for his users. This is just a guess. 

however i recommend this should be changed to something like a zip folder link or maybe even a gdrive link. chrome and such browsers do a really good job of scaring people

**Comment by BasilSkrnk** [comment]
Hey @pranavnasrani, thanks for your thorough explanation! I wasn’t too worried as I’m on (Arch) Linux. But still, the browser alert scared me off indeed! I did not download the archive, even following the original repository link. (Perhaps, I partly forgot about that intention after reporting the issue.)

> any particular reason why you want to download them?

Not really. I thought I have everything (too much of everything) upon git cloning the repository, and was just curious is there something _else_, that it’s mentioned in the Readme, or it’s just for redundancy. 

Anyway, the newer approach is better, I’d say.

I never paid attention that GitHub doesn’t allow downloading the entire directory. I’m mostly a GitLab user, and it’s in there since I can remember, I had no issues downloading any directory.
