### ISSUE TITLE
issue build

### ISSUE THREAD

**Issue by bienpierre** [nunocoracao/blowfish#20]
Hello, 

I have an issue to build with the blowfish theme:

For instance, I did:

1) I download the exampleSite on this repos. In the config.toml there is the theme= "blowfish", so I install the theme using git.

2) Then I tried to build the site (hugo), however I have a issue: 

![image](https://user-images.githubusercontent.com/50803547/191924993-2bbc8701-3ce8-43b9-ab04-695b4b6c5606.png)

3) The public/index.html render is wrong: 

![image](https://user-images.githubusercontent.com/50803547/191926081-31db5a2c-2a4a-41da-ab0a-a001a954c8a4.png)

The goversion is go version go1.19 linux/amd64 and I installed Hugo with the snap package.

I do not know what to do.

regards

**Comment by nunocoracao** [comment]
Hello @bienpierre could you provide more details on how you installed the theme? Did you follow the steps in this guide
https://nunocoracao.github.io/blowfish/docs/installation/

**Comment by bienpierre** [comment]
Hello, 

I used hugo to installed the theme. 

The differences that I note, is that I installed golang with the rpm from the opensuse.

Also,  when launching : `hugo server -D`, the page looks good.

Regards

**Comment by nunocoracao** [comment]
@bienpierre I followed the exact same steps and it worked for me. I would advise you to look at https://nunocoracao.github.io/blowfish/docs/installation/ to check if you missed something. Another option is that this might be a bug on Hugo itself for the platform you are using. I am closing the ticket because it seems there is nothing to fix, if you have more information feel free to reopen and attach it so I can check again. Thanks
