### ISSUE TITLE
✨Color scheme support for images.

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#251]
**Is your feature request related to a problem? Please describe.**

It is annoying that the png/gif I am using in some of the pages looks ok in the dark theme (white icon), but is barely visible in the light theme.

**Describe the solution you'd like**

We should be able to have 2 versions for each image, say `image.dark.png` and `image.light.png` and the theme should automatically select the appropriate one for the current color scheme.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

**Comment by nunocoracao** [comment]
@mirceanton this won't work. Both images must be baked into the code and processed by the Hugo pipelines to be displayed. My current thoughts are that it is an override for a specific image for dark mode EVERYWHERE. But this is not a scalable option.

**Comment by madoke** [comment]
The problem here is that images are processed in build time and the theme is rendered in runtime. It would be hard to make this dynamic for every image. One possible alternative could be loading both `.light` and `.dark` files and use tailwind classes to change between them like its described [here](https://www.ibrahima-ndaw.com/blog/tailwindcss-background-image-with-dark-mode-support/)

**Comment by nunocoracao** [comment]
No easy way to do this as not all images use `img` tag and therefore the render hook is not feasible. Closing
