### ISSUE TITLE
🐛 Move to top gap between content and icon

### ISSUE THREAD

**Issue by rpstreef** [nunocoracao/blowfish#696]
**Describe the bug**
There's quite some padding between the content and the move to top icon

**To Reproduce**
1. Go to any list view page with the move to top enabled
2. Scroll all the way down
3. There's a big gap between the content and the icon

**Expected behavior**
The icon should have sensible amount of padding from the content

**Screenshots**
![Screenshot_20230501_131350](https://user-images.githubusercontent.com/15830262/235415576-664791c2-2e8a-4dac-aac2-ed815a2accac.png)

**Desktop (please complete the following information):**
 - OS: Linux, KDE Neon
 - Browser Firefox
 - Version 112.0.2

**Hugo & Blowfish versions**
Hugo: v0.111.3+extended linux/amd64 BuildDate=unknown
Blowfish: v2.32.1

**Comment by nunocoracao** [comment]
@rpstreef not able to reproduce, Blowfish page doesn't have that problem. Could you please re-check with latest version and update the details of the ticket so that it's easy to reproduce? Thanks

![Screenshot 2023-05-01 at 10 29 44](https://user-images.githubusercontent.com/3803196/235435085-5da8432a-7073-4827-8dd8-22fe975c3afe.png)

**Comment by rpstreef** [comment]
Please review this git repo:

https://github.com/rpstreef/hugo-blowfish-test

I've reproduced the problem

**Comment by nunocoracao** [comment]
Will check. Since you have the code on your side, if possible, could you do me a quick test - try removing some of the footer menu items and see if that margin reduces itself? I think that could be the culprit
