### ISSUE TITLE
Hugo wont parse new appearance.js

### ISSUE THREAD

**Issue by amino-8** [nunocoracao/blowfish#727]
I just updated blowfish from 2.33.0 to 2.33.2 and when I try to build my site I get the following error:
```
Start building sites …
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
INFO 2023/05/17 11:47:45 syncing static files to /
Error: Error building site: MINIFY: failed to transform "js/appearance.js" (text/javascript): expected ( instead of and in if statement on line 74 and column 7
   74: {{ if and (.Site.Params.Logo) (.Site.Params.SecondaryLogo...
             ^
Total in 330 ms
```

I checked the PR logs and it looks like everything builds ok through the autobuild workflow so could this be a problem with my environment?

**Comment by schachem** [comment]
Had the same issue initially.  
The fault does not lie with the theme.

In my case I had overwritten `layouts/partials/head.html` because I needed some custom modifications.
Is suspect you did the same, otherwise, I do not know what could cause the issue.

You should update the mentioned file and then incorporate your custom changes again.

**Comment by amino-8** [comment]
Ahhh, I hadn't even considered that! That fixed my issue. Thank you for the heads up!

**Comment by nunocoracao** [comment]
Thanks for the help @schachem
